with retail as (
select (case when xsimcardno='Corporate' or xbloodgrp='SENA KALYAN' or xbloodgrp='Office Sales' then (select max(xzone) from cadelpoint where xthana=h.xdelpoint) else c.xbloodgrp end) Zone_name,h.xcus,c.xorg,h.xwh,h.xdelivery,xvehicle,xsornum, xconfirmt,h.xchlnum,
(d.xqtychl) total,case when xsimcardno='Corporate'  then d.xqtychl else 0 end Corporate,
case when h.xwh='FINISHED GOODS' and  h.xdelivery='Company' and  d.xtypecat not like '%BULK%' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Fi_OwnTruck,
case when h.xwh='FINISHED GOODS' and  h.xdelivery='Company' and  d.xtypecat like '%BULK%' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Fi_OwnBulk,
case when h.xwh='FINISHED GOODS' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Fi_RentalTruck,
case when h.xwh='FINISHED GOODS' and h.xdelivery='Customer' then d.xqtychl else 0 end Fi_CustomerTruck,
case when h.xwh='Noapara Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end NO_OwnTruck,
case when h.xwh='Noapara Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end NO_RentalTruck,
case when h.xwh='Noapara Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end NO_CustomerTruck,
case when h.xwh='Kaligonj Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Ka_OwnTruck,
case when h.xwh='Kaligonj Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Ka_RentalTruck,
case when h.xwh='Kaligonj Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end Ka_CustomerTruck,
case when h.xwh='C & B(Faridpur) Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end CN_OwnTruck,
case when h.xwh='C & B(Faridpur) Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end CN_RentalTruck,
case when h.xwh='C & B(Faridpur) Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end CN_CustomerTruck,
case when h.xwh='Shunamgonj Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Sh_OwnTruck,
case when h.xwh='Shunamgonj Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Sh_RentalTruck,
case when h.xwh='Shunamgonj Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end Sh_CustomerTruck,
case when h.xwh='Daudkandi Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Da_OwnTruck,
case when h.xwh='Daudkandi Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Da_RentalTruck,
case when h.xwh='Daudkandi Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end Da_CustomerTruck,
case when h.xwh='Diabari ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Di_OwnTruck,
case when h.xwh='Diabari ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Di_RentalTruck,
case when h.xwh='Diabari ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end Di_CustomerTruck,
case when h.xwh='Tekerhat Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Te_OwnTruck,
case when h.xwh='Tekerhat Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Te_RentalTruck,
case when h.xwh='Tekerhat Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end Te_CustomerTruck,
case when h.xwh='NogorBari Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end NG_OwnTruck,
case when h.xwh='NogorBari Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end NG_RentalTruck,
case when h.xwh='NogorBari Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end NG_CustomerTruck,
case when h.xwh='Ashugonj Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end As_OwnTruck,
case when h.xwh='Ashugonj Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end As_RentalTruck,
case when h.xwh='Ashugonj Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end As_CustomerTruck,
case when h.xwh='Scan Cement Factory' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Sc_OwnTruck,
case when h.xwh='Scan Cement Factory' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Sc_RentalTruck,
case when h.xwh='Scan Cement Factory' and h.xdelivery='Customer' then d.xqtychl else 0 end Sc_CustomerTruck,
case when h.xwh='Barisal Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Ba_OwnTruck,
case when h.xwh='Barisal Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Ba_RentalTruck,
case when h.xwh='Barisal Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end Ba_CustomerTruck,
case when h.xwh='Amin Bazar Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Am_OwnTruck,
case when h.xwh='Amin Bazar Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Am_RentalTruck,
case when h.xwh='Amin Bazar Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end Am_CustomerTruck,
case when h.xwh='Mongla Cement Factory' and  d.xtypecat not like '%BULK%' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Mo_OwnTruck,
case when h.xwh='Mongla Cement Factory' and  d.xtypecat like '%BULK%' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Mo_OwnBulk,
case when h.xwh='Mongla Cement Factory' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Mo_RentalTruck,
case when h.xwh='Mongla Cement Factory' and h.xdelivery='Customer' then d.xqtychl else 0 end Mo_CustomerTruck
from opchallan h join opchalland d on h.zid=d.zid and h.xchlnum=d.xchlnum
join cacus c on c.zid=h.zid and c.xcus=h.xcus  
where   CONVERT(date,DATEADD(HOUR,-6,xconfirmt)) between '2021-01-01' and '2021-04-30' and xsimcardno<>'Bag Plant'
)
select Zone_name,sum(total)/80 Total ,sum(Corporate)/80 Corporate,
sum(Fi_OwnTruck)/80 Fi_OwnTruck ,sum(Fi_OwnBulk)/80 Fi_OwnBulk, sum(Fi_RentalTruck)/80 Fi_RentalTruck,sum(Fi_CustomerTruck)/80 Fi_CustomerTruck,
sum(NO_OwnTruck)/80 NO_OwnTruck ,sum(NO_RentalTruck)/80 NO_RentalTruck,sum(NO_CustomerTruck)/80 NO_CustomerTruck,
sum(Ka_OwnTruck)/80 Ka_OwnTruck ,sum(Ka_RentalTruck)/80 Ka_RentalTruck,sum(Ka_CustomerTruck)/80 Ka_CustomerTruck,
sum(CN_OwnTruck)/80 CN_OwnTruck ,sum(CN_RentalTruck)/80 CN_RentalTruck,sum(CN_CustomerTruck)/80 CN_CustomerTruck,
sum(Sh_OwnTruck)/80 Sh_OwnTruck ,sum(Sh_RentalTruck)/80 Sh_RentalTruck,sum(Sh_CustomerTruck)/80 Sh_CustomerTruck,
sum(Da_OwnTruck)/80 Da_OwnTruck ,sum(Da_RentalTruck)/80 Da_RentalTruck,sum(Da_CustomerTruck)/80 Da_CustomerTruck,
sum(Di_OwnTruck)/80 Di_OwnTruck ,sum(Di_RentalTruck)/80 Di_RentalTruck,sum(Di_CustomerTruck)/80 Di_CustomerTruck,
sum(Te_OwnTruck)/80 Te_OwnTruck ,sum(Te_RentalTruck)/80 Te_RentalTruck,sum(Te_CustomerTruck)/80 Te_CustomerTruck,
sum(NG_OwnTruck)/80 NG_OwnTruck ,sum(Ng_RentalTruck)/80 NG_RentalTruck,sum(NG_CustomerTruck)/80 NG_CustomerTruck,
sum(As_OwnTruck)/80 As_OwnTruck ,sum(As_RentalTruck)/80 As_RentalTruck,sum(As_CustomerTruck)/80 As_CustomerTruck,
sum(Sc_OwnTruck)/80 Sc_OwnTruck ,sum(Sc_RentalTruck)/80 Sc_RentalTruck,sum(Sc_CustomerTruck)/80 Sc_CustomerTruck,
sum(Ba_OwnTruck)/80 Ba_OwnTruck ,sum(Ba_RentalTruck)/80 Ba_RentalTruck,sum(Ba_CustomerTruck)/80 Ba_CustomerTruck,
sum(Am_OwnTruck)/80 Am_OwnTruck ,sum(Am_RentalTruck)/80 Am_RentalTruck,sum(Am_CustomerTruck)/80 Am_CustomerTruck,
sum(Mo_OwnTruck)/80 Mo_OwnTruck ,sum(Mo_OwnBulk)/80 Mo_OwnBulk ,sum(Mo_RentalTruck)/80 Mo_RentalTruck,sum(Mo_CustomerTruck)/80 Mo_CustomerTruck
from retail a 
group by Zone_name
order by Zone_name


with retail as (
select  c.xbloodgrp  Zone_name,(select xdistrict from cadelpoint where xthana=h.xdelpoint) xdistrict ,h.xdelpoint xthana, h.xcus,c.xorg,h.xwh,h.xdelivery,xvehicle,xsornum, xconfirmt,h.xchlnum,
(d.xqtychl) total,
case when h.xwh='FINISHED GOODS' and  h.xdelivery='Company' and  d.xtypecat not like '%BULK%' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Fi_OwnTruck,
case when h.xwh='FINISHED GOODS' and  h.xdelivery='Company' and  d.xtypecat like '%BULK%' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Fi_OwnBulk,
case when h.xwh='FINISHED GOODS' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Fi_RentalTruck,
case when h.xwh='FINISHED GOODS' and h.xdelivery='Customer' then d.xqtychl else 0 end Fi_CustomerTruck,
case when h.xwh='Noapara Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end NO_OwnTruck,
case when h.xwh='Noapara Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end NO_RentalTruck,
case when h.xwh='Noapara Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end NO_CustomerTruck,
case when h.xwh='Kaligonj Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Ka_OwnTruck,
case when h.xwh='Kaligonj Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Ka_RentalTruck,
case when h.xwh='Kaligonj Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end Ka_CustomerTruck,
case when h.xwh='C & B(Faridpur) Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end CN_OwnTruck,
case when h.xwh='C & B(Faridpur) Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end CN_RentalTruck,
case when h.xwh='C & B(Faridpur) Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end CN_CustomerTruck,
case when h.xwh='Shunamgonj Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Sh_OwnTruck,
case when h.xwh='Shunamgonj Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Sh_RentalTruck,
case when h.xwh='Shunamgonj Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end Sh_CustomerTruck,
case when h.xwh='Daudkandi Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Da_OwnTruck,
case when h.xwh='Daudkandi Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Da_RentalTruck,
case when h.xwh='Daudkandi Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end Da_CustomerTruck,
case when h.xwh='Diabari ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Di_OwnTruck,
case when h.xwh='Diabari ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Di_RentalTruck,
case when h.xwh='Diabari ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end Di_CustomerTruck,
case when h.xwh='Tekerhat Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Te_OwnTruck,
case when h.xwh='Tekerhat Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Te_RentalTruck,
case when h.xwh='Tekerhat Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end Te_CustomerTruck,
case when h.xwh='NogorBari Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end NG_OwnTruck,
case when h.xwh='NogorBari Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end NG_RentalTruck,
case when h.xwh='NogorBari Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end NG_CustomerTruck,
case when h.xwh='Ashugonj Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end As_OwnTruck,
case when h.xwh='Ashugonj Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end As_RentalTruck,
case when h.xwh='Ashugonj Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end As_CustomerTruck,
case when h.xwh='Scan Cement Factory'  and  d.xtypecat not like '%BULK%' and  h.xdelivery='Company'  and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Sc_OwnTruck,
case when h.xwh='Scan Cement Factory'  and  d.xtypecat  like '%BULK%' and  h.xdelivery='Company'  and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Sc_OwnBulk,
case when h.xwh='Scan Cement Factory' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Sc_RentalTruck,
case when h.xwh='Scan Cement Factory' and h.xdelivery='Customer' then d.xqtychl else 0 end Sc_CustomerTruck,
case when h.xwh='Barisal Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Ba_OwnTruck,
case when h.xwh='Barisal Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Ba_RentalTruck,
case when h.xwh='Barisal Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end Ba_CustomerTruck,
case when h.xwh='Amin Bazar Ghat' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Am_OwnTruck,
case when h.xwh='Amin Bazar Ghat' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Am_RentalTruck,
case when h.xwh='Amin Bazar Ghat' and h.xdelivery='Customer' then d.xqtychl else 0 end Am_CustomerTruck,
case when h.xwh='Mongla Cement Factory' and  d.xtypecat not like '%BULK%' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Mo_OwnTruck,
case when h.xwh='Mongla Cement Factory' and  d.xtypecat like '%BULK%' and  h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is not null then d.xqtychl else 0 end Mo_OwnBulk,
case when h.xwh='Mongla Cement Factory' and h.xdelivery='Company' and (select xvehicle from vmvech where xvehicle=h.xvehicle) is  null then d.xqtychl else 0 end Mo_RentalTruck,
case when h.xwh='Mongla Cement Factory' and h.xdelivery='Customer' then d.xqtychl else 0 end Mo_CustomerTruck
from opchallan h join opchalland d on h.zid=d.zid and h.xchlnum=d.xchlnum
join cacus c on c.zid=h.zid and c.xcus=h.xcus  
where   CONVERT(date,DATEADD(HOUR,-6,xconfirmt)) between '2021-01-01' and '2021-04-30' and xsimcardno='Corporate'  --not in ('Bag Plant','Corporate')
)
select Zone_name,xdistrict , xthana,sum(total)/80 Total ,
sum(Fi_OwnTruck)/80 Fi_OwnTruck ,sum(Fi_OwnBulk)/80 Fi_OwnBulk, sum(Fi_RentalTruck)/80 Fi_RentalTruck,sum(Fi_CustomerTruck)/80 Fi_CustomerTruck,
sum(NO_OwnTruck)/80 NO_OwnTruck ,sum(NO_RentalTruck)/80 NO_RentalTruck,sum(NO_CustomerTruck)/80 NO_CustomerTruck,
sum(Ka_OwnTruck)/80 Ka_OwnTruck ,sum(Ka_RentalTruck)/80 Ka_RentalTruck,sum(Ka_CustomerTruck)/80 Ka_CustomerTruck,
sum(CN_OwnTruck)/80 CN_OwnTruck ,sum(CN_RentalTruck)/80 CN_RentalTruck,sum(CN_CustomerTruck)/80 CN_CustomerTruck,
sum(Sh_OwnTruck)/80 Sh_OwnTruck ,sum(Sh_RentalTruck)/80 Sh_RentalTruck,sum(Sh_CustomerTruck)/80 Sh_CustomerTruck,
sum(Da_OwnTruck)/80 Da_OwnTruck ,sum(Da_RentalTruck)/80 Da_RentalTruck,sum(Da_CustomerTruck)/80 Da_CustomerTruck,
sum(Di_OwnTruck)/80 Di_OwnTruck ,sum(Di_RentalTruck)/80 Di_RentalTruck,sum(Di_CustomerTruck)/80 Di_CustomerTruck,
sum(Te_OwnTruck)/80 Te_OwnTruck ,sum(Te_RentalTruck)/80 Te_RentalTruck,sum(Te_CustomerTruck)/80 Te_CustomerTruck,
sum(NG_OwnTruck)/80 NG_OwnTruck ,sum(Ng_RentalTruck)/80 NG_RentalTruck,sum(NG_CustomerTruck)/80 NG_CustomerTruck,
sum(As_OwnTruck)/80 As_OwnTruck ,sum(As_RentalTruck)/80 As_RentalTruck,sum(As_CustomerTruck)/80 As_CustomerTruck,
sum(Sc_OwnTruck)/80 Sc_OwnTruck ,sum(Sc_OwnBulk)/80 Sc_OwnBulk, sum(Sc_RentalTruck)/80 Sc_RentalTruck,sum(Sc_CustomerTruck)/80 Sc_CustomerTruck,
sum(Ba_OwnTruck)/80 Ba_OwnTruck ,sum(Ba_RentalTruck)/80 Ba_RentalTruck,sum(Ba_CustomerTruck)/80 Ba_CustomerTruck,
sum(Am_OwnTruck)/80 Am_OwnTruck ,sum(Am_RentalTruck)/80 Am_RentalTruck,sum(Am_CustomerTruck)/80 Am_CustomerTruck,
sum(Mo_OwnTruck)/80 Mo_OwnTruck ,sum(Mo_OwnBulk)/80 Mo_OwnBulk ,sum(Mo_RentalTruck)/80 Mo_RentalTruck,sum(Mo_CustomerTruck)/80 Mo_CustomerTruck
from retail a 
group by  Zone_name,xdistrict , xthana
order by  Zone_name,xdistrict , xthana
